import { Theme } from "@/styles/theme";
import { Platform, StyleSheet } from "react-native";

const textStyles = (theme: Theme) => StyleSheet.create({
  text: {
    fontSize: theme.typography.fontSize.base,
    fontFamily: theme.typography.fontFamily.regular,
    color: theme.colors.text.primary,
    letterSpacing: 2,
    // lineHeight: Platform.OS === "android" ? 24 : undefined,
    includeFontPadding: false,
  },
  h1_extraBold: {
    fontSize: theme.typography.fontSize['4xl'],
    fontFamily: theme.typography.fontFamily.extraBold,
    color: theme.colors.text.primary,
    // lineHeight: Platform.OS === "android" ? 54 : undefined,
    includeFontPadding: false,
  },
  h2_extraBold: {
    fontSize: theme.typography.fontSize['3xl'],
    fontFamily: theme.typography.fontFamily.extraBold,
    color: theme.colors.text.primary,
    // lineHeight: Platform.OS === "android" ? 44 : undefined,
    includeFontPadding: false,
  },
  h3_extraBold: {
    fontSize: theme.typography.fontSize['2xl_bold'],
    fontFamily: theme.typography.fontFamily.extraBold,
    color: theme.colors.text.primary,
    // lineHeight: Platform.OS === "android" ? 34 : undefined,
    includeFontPadding: false,
  },
  h3_bold: {
    fontSize: theme.typography.fontSize['2xl_bold'],
    fontFamily: theme.typography.fontFamily.bold,
    color: theme.colors.text.primary,
    // lineHeight: Platform.OS === "android" ? 34 : undefined,
    includeFontPadding: false,
  },
  h4_bold: {
    fontSize: theme.typography.fontSize['2xl'],
    fontFamily: theme.typography.fontFamily.bold,
    color: theme.colors.text.primary,
    // lineHeight: Platform.OS === "android" ? 34 : undefined,
    includeFontPadding: false,
  },
  body20_bold: {
    fontSize: theme.typography.fontSize.xl,
    fontFamily: theme.typography.fontFamily.bold,
    color: theme.colors.text.primary,
    // lineHeight: Platform.OS === "android" ? 28 : undefined,
    includeFontPadding: false,
  },
  body20_medium: {
    fontSize: theme.typography.fontSize.xl,
    fontFamily: theme.typography.fontFamily.medium,
    color: theme.colors.text.secondary,
    letterSpacing: theme.typography.letterSpacing.normal,
    // lineHeight: Platform.OS === "android" ? 28 : undefined,
    includeFontPadding: false,
  },
  body18_bold: {
    fontSize: theme.typography.fontSize.lg,
    fontFamily: theme.typography.fontFamily.bold,
    color: theme.colors.text.secondary,
    letterSpacing: theme.typography.letterSpacing.tight,
    // lineHeight: Platform.OS === "android" ? 21 : undefined,
    includeFontPadding: false,
  },
  body18_medium: {
    fontSize: theme.typography.fontSize.lg,
    fontFamily: theme.typography.fontFamily.medium,
    color: theme.colors.text.secondary,
    letterSpacing: theme.typography.letterSpacing.normal,
    // lineHeight: Platform.OS === "android" ? 21 : undefined,
    includeFontPadding: false,
  },
  body16_bold: {
    fontSize: theme.typography.fontSize.base,
    fontFamily: theme.typography.fontFamily.bold,
    color: theme.colors.text.secondary,
    letterSpacing: theme.typography.letterSpacing.tight,
    // lineHeight: Platform.OS === "android" ? 21 : undefined,
    includeFontPadding: false,
  },
  body16_medium: {
    fontSize: theme.typography.fontSize.base,
    fontFamily: theme.typography.fontFamily.medium,
    color: theme.colors.text.secondary,
    letterSpacing: theme.typography.letterSpacing.normal,
    // lineHeight: Platform.OS === "android" ? 21 : undefined,
    includeFontPadding: false,
  },
  body14_medium: {
    fontSize: theme.typography.fontSize.sm,
    fontFamily: theme.typography.fontFamily.medium,
    color: theme.colors.text.secondary,
    letterSpacing: theme.typography.letterSpacing.tight,
    // lineHeight: Platform.OS === "android" ? 18 : undefined,
    includeFontPadding: false,
  },
  body14_bold: {
    fontSize: theme.typography.fontSize.sm,
    fontFamily: theme.typography.fontFamily.bold,
    color: theme.colors.text.secondary,
    letterSpacing: theme.typography.letterSpacing.tight,
    // lineHeight: Platform.OS === "android" ? 18 : undefined,
    includeFontPadding: false,
  },
  body12_medium: {
    fontSize: theme.typography.fontSize.xs,
    fontFamily: theme.typography.fontFamily.medium,
    color: theme.colors.text.secondary,
    letterSpacing: theme.typography.letterSpacing.tight,
    // lineHeight: Platform.OS === "android" ? 18 : undefined,
    includeFontPadding: false,
  },
  body12_bold: {
    fontSize: theme.typography.fontSize.xs,
    fontFamily: theme.typography.fontFamily.bold,
    color: theme.colors.text.secondary,
    // lineHeight: Platform.OS === "android" ? 18 : undefined,
    includeFontPadding: false,
  },
  button: {
    fontSize: theme.typography.fontSize['xl'],
    textAlign: 'center',
    fontFamily: theme.typography.fontFamily.semiBold,
    color: theme.colors.basic.white,
    letterSpacing: theme.typography.letterSpacing.tight as any,
    // lineHeight: Platform.OS === "android" ? 28 : undefined,
    includeFontPadding: false,
  },
  button_brand: {
    fontSize: theme.typography.fontSize['xl'],
    textAlign: 'center',
    fontFamily: theme.typography.fontFamily.semiBold,
    color: theme.colors.text.primary,
    letterSpacing: theme.typography.letterSpacing.tight as any,
    // lineHeight: Platform.OS === "android" ? 28 : undefined,
    includeFontPadding: false,
  },
  error: {
    fontFamily: theme.typography.fontFamily.medium,
    color: theme.colors.semantic.error,
    fontSize: theme.typography.fontSize.base,
  },
  currency: {
    fontSize: 24,
    fontFamily: theme.typography.fontFamily.extraBold,
    color: theme.colors.text.currency,
    verticalAlign: 'middle',
    // lineHeight: Platform.OS === "android" ? 40 : undefined,
    includeFontPadding: false,
  },
  bigTitle: {
    fontSize: 86,
    verticalAlign: 'middle',
    fontFamily: theme.typography.fontFamily.extraBold,
    color: theme.colors.text.currency,
    includeFontPadding: false,
  },
});

export default textStyles;